var levels = [
    {
        characters:[
            {
                name: "rat",
                x: 80,
                y: 100,
                deltaX: 0,
                deltaY: 0,
                airborne: true,
                height: 20,
                width: 20,
                color: "#228B22",
                up: 38,
                left: 37,
                right: 39,
                gravity: 0.2,
                jumpStrength: -6,
            },
            {
                name: "bat",
                x: 300,
                y: 500,
                deltaX: 0,
                deltaY: 0,
                airborne: true,
                height: 30,
                width: 30,
                color: "#D2691E",
                up: 87,
                left: 65,
                right: 68,
                gravity: 0.2,
                jumpStrength: -6,
            }
        ],
        platforms:[
            {
                x: 10,
                y: 150,
                width: 1000,
                height: 10,
                active: true,
            },
            {
                x: 10,
                y: 600,
                width: 1000,
                height: 10,
                active: true,
            },
            {
                x: 120,
                y: 10,
                width: 10,
                height: 140,
                active: true,
                group: "group1",
            },
            {
                x: 400,
                y: 550,
                width: 120,
                height: 10,
                active: false,
                group: "group2",
            },
            {
                x: 300,
                y: 480,
                width: 120,
                height: 10,
                active: false,
                group: "group2",
            },
            {
                x: 200,
                y: 400,
                width: 120,
                height: 10,
                active: false,
                group: "group2",
            },
            {
                x: 10,
                y: 320,
                width: 150,
                height: 10,
                active: true,
                group: "",
            },
            {
                x: 1120,
                y: 150,
                width: 150,
                height: 10,
                active: true,
            },
            {
                x: 620,
                y: 250,
                width: 450,
                height: 10,
                active: false,
                group: "group3",
            },
        ],
        coins:[
            {
                x: 600,
                y: 530,
                active: true,
                radius: 13,
            },
            {
                x: 200,
                y: 130,
                active: true,
                radius: 13,
            },
            {
                x: 250,
                y: 60,
                active: true,
                radius: 13,
            },
            {
                x: 300,
                y: 130,
                active: true,
                radius: 13,
            },
            {
                x: 350,
                y: 60,
                active: true,
                radius: 13,
            },
            {
                x: 740,
                y: 200,
                active: true,
                radius: 13,
            },
            {
                x: 790,
                y: 200,
                active: true,
                radius: 13,
            },
        ],
        buttons:[
            {
                x: 120,
                y: 585,
                height: 15,
                width: 20,
                base_height: 5,
                active: true,
                group: "group1",
                color: "#DC143C", //"#2CD307"
            },
            {
                x: 400,
                y: 135,
                height: 15,
                width: 20,
                base_height: 5,
                active: true,
                group: "group2",
                color: "#2CD307", //"#DC143C"
            },
            {
                x: 50,
                y: 305,
                height: 15,
                width: 20,
                base_height: 5,
                active: true,
                group: "group3",
                color: "#FFFF00", //"#DC143C"
            },
        ],
    },
];

var base_platforms = [{
    x: 0,
    y: 0,
    width: 10,
    height: 710,
    active: true,
},
{
    x: 0,
    y: 710,
    width: 1270,
    height: 10,
    active: true,
},
{
    x: 10,
    y: 0,
    width: 1270,
    height: 10,
    active: true,
},
{
    x: 1270,
    y: 10,
    width: 10,
    height: 710,
    active: true,
}
];