var levels = [
    {
        characters:[
            {
                name: "rat",
                x: 80,
                y: 100,
                deltaX: 0,
                deltaY: 0,
                airborne: true,
                height: 20,
                width: 20,
                color: "#228B22",
                up: 38,
                left: 37,
                right: 39,
                gravity: 0.2,
                jumpStrength: -6,
            },
            {
                name: "bat",
                x: 100,
                y: 500,
                deltaX: 0,
                deltaY: 0,
                airborne: true,
                height: 30,
                width: 30,
                color: "#D2691E",
                up: 87,
                left: 65,
                right: 68,
                gravity: 0.2,
                jumpStrength: -6,
            }
        ],
        platforms:[
            {
                x: 10,
                y: 150,
                width: 1000,
                height: 10,
                active: true,
            },
            {
                x: 10,
                y: 620,
                width: 1000,
                height: 10,
                active: true,
            },
            {
                x: 1120,
                y: 150,
                width: 150,
                height: 10,
                active: true,
            },
            {
                x: 10,
                y: 360,
                width: 1260,
                height: 10,
                active: true,
            },
            {
                x: 1120,
                y: 550,
                width: 150,
                height: 10,
                active: true,
            },
            {
                x: 10,
                y: 490,
                width: 1000,
                height: 10,
                active: true,
            },
            {
                x: 100,
                y: 270,
                width: 100,
                height: 10,
                active: true,
            },
            {
                x: 200,
                y: 320,
                width: 100,
                height: 10,
                active: true,
            },
            {
                x: 400,
                y: 270,
                width: 100,
                height: 10,
                active: true,
            },
            {
                x: 500,
                y: 320,
                width: 100,
                height: 10,
                active: true,
            },
            {
                x: 700,
                y: 270,
                width: 100,
                height: 10,
                active: true,
            },
            {
                x: 800,
                y: 320,
                width: 100,
                height: 10,
                active: true,
            },    
            {
                x: 700,
                y: 160,
                width: 10,
                height: 110,
                active: true,
            }, 
            {
                x: 590,
                y: 150,
                width: 10,
                height: 170,
                active: true,
            },
            {
                x: 600,
                y: 290,
                width: 10,
                height: 10,
                active: true,
            },
            {
                x: 10,
                y: 300,
                width: 10,
                height: 10,
                active: true,
            },
            {
                x: 300,
                y: 160,
                width: 10,
                height: 170,
                active: true,
            },
            {
                x: 200,
                y: 270,
                width: 10,
                height: 60,
                active: true,
            },
            {
                x: 500,
                y: 90,
                width: 10,
                height: 60,
                active: true,
            },
            {
                x: 800,
                y: 90,
                width: 10,
                height: 60,
                active: true,
            },
            {
                x: 900,
                y: 90,
                width: 10,
                height: 60,
                active: true,
            },
            {
                x: 810,
                y: 90,
                width: 90,
                height: 10,
                active: true,
            },
            {
                x: 1000,
                y: 620,
                width: 10,
                height: 90,
                active: true,
            },
            {
                x: 1050,
                y: 670,
                width: 10,
                height: 40,
                active: true,
            },
            {
                x: 1010,
                y: 660,
                width: 50,
                height: 10,
                active: true,
            },
            {
                x: 920,
                y: 430,
                width: 60,
                height: 10,
                active: true,
            },
            {
                x: 970,
                y: 440,
                width: 10,
                height: 50,
                active: true,
            },
            {
                x: 800,
                y: 430,
                width: 60,
                height: 10,
                active: true,
            },
            {
                x: 850,
                y: 370,
                width: 10,
                height: 60,
                active: true,
            },
            {
                x: 530,
                y: 430,
                width: 60,
                height: 10,
                active: true,
            },
            {
                x: 580,
                y: 440,
                width: 10,
                height: 50,
                active: true,
            },
            {
                x: 400,
                y: 430,
                width: 60,
                height: 10,
                active: true,
            },
            {
                x: 450,
                y: 370,
                width: 10,
                height: 60,
                active: true,
            },
            {
                x: 130,
                y: 430,
                width: 60,
                height: 10,
                active: true,
            },
            {
                x: 180,
                y: 440,
                width: 10,
                height: 50,
                active: true,
            },
            {
                x: 000,
                y: 430,
                width: 60,
                height: 10,
                active: true,
            },
        ],
        coins:[
            {
                x: 600,
                y: 530,
                active: true,
                radius: 13,
            },
            {
                x: 150,
                y: 250,
                active: true,
                radius: 13,
            },
            {
                x: 750,
                y: 250,
                active: true,
                radius: 13,
            },
            {
                x: 250,
                y: 300,
                active: true,
                radius: 13,
            },
            {
                x: 450,
                y: 250,
                active: true,
                radius: 13,
            },
            {
                x: 550,
                y: 300,
                active: true,
                radius: 13,
            },
            {
                x: 650,
                y: 190,
                active: true,
                radius: 13,
            },
            {
                x: 1170,
                y: 320,
                active: true,
                radius: 13,
            },
            {
                x: 900,
                y: 530,
                active: true,
                radius: 13,
            },
            {
                x: 750,
                y: 580,
                active: true,
                radius: 13,
            },
            {
                x: 1250,
                y: 500,
                active: true,
                radius: 13,
            },
            {
                x: 1250,
                y: 640,
                active: true,
                radius: 13,
            },
            {
                x: 950,
                y: 470,
                active: true,
                radius: 13,
            },
            {
                x: 560,
                y: 470,
                active: true,
                radius: 13,
            },
            {
                x: 160,
                y: 470,
                active: true,
                radius: 13,
            },
            {
                x: 30,
                y: 470,
                active: true,
                radius: 13,
            },
            {
                x: 160,
                y: 400,
                active: true,
                radius: 13,
            },
            {
                x: 30,
                y: 400,
                active: true,
                radius: 13,
            },
            {
                x: 425,
                y: 400,
                active: true,
                radius: 13,
            },
            {
                x: 825,
                y: 400,
                active: true,
                radius: 13,
            },
        ],
        buttons:[
        ],
        texts:[
            {
                x: 1280 / 4,
                y: 100,
                text: "Move using arrow keys",
                font:"30px Comic Sans MS",
                color: "green",
            },
            {
                x: 1280 / 4,
                y: 530,
                text: "Move using WSAD",
                font:"30px Comic Sans MS",
                color: "darkorange",
            },
            {
                x: 1280 / 2,
                y: 230,
                text: "Collect all the coins!",
                font:"34px Comic Sans MS",
                color: "brown",
            },
        ],
    },
];

var base_platforms = [{
    x: 0,
    y: 0,
    width: 10,
    height: 710,
    active: true,
},
{
    x: 0,
    y: 710,
    width: 1270,
    height: 10,
    active: true,
},
{
    x: 10,
    y: 0,
    width: 1270,
    height: 10,
    active: true,
},
{
    x: 1270,
    y: 10,
    width: 10,
    height: 710,
    active: true,
}
];